10minrms_ds.py*
APEX_weather.py@
APEX_weather.pyc
averageGains.py*
barcoder.py*
buildAccept.py*
buildAccept.pyc
calculate_SS_contrib.py*
capture.py*
ces_translate.py*
ces_translate.pyc
chiconly.txt
colonly.txt
compare_acceptlists.py*
compareAcceptlists.py*
confidence.py*
conversion/
convertGains.py*
convertSQLtoAccept.py*
cuts/
cuts2accept.py*
cuts.cmd
dataExtractionExample.py*
dead.cut
differenceNoiseMap.py*
differenceNoiseMap.pyc
diff.txt
diode_maps.py
extensions/
extractSigmas.py*
fitPowerSpectrum.py*
generateBatch.py*
generateMLAccept.py*
generateOsloAccept.py*
generatePCLAccept.py*
getcestime.py*
getSigma.py*
gnuplot.py*
jackknifeAccept.py*
make_accept_from_list.py*
makeBlindTest.py*
makeCESRuns.py*
makeDifferenceMap.py*
makeDifferenceMap.pyc
makeFakeParamDatabase.py*
makeJackknives_091130.py*
makeJackknives_091130.pyc
make_jackknives.py*
makeJackknives.py*
makeJackknives.pyc
makeNoiseWeightedMap.py*
makeNoiseWeightedMap.pyc
makeNullRuns.py*
makeNullRuns.pyc
makeRun.py*
makeRun.pyc
makeRun_singlev.py*
makeWeatherAccept.py*
mapping.py
meanGains.py*
mpiExample.py*
mpiHelloWorld.py*
nulltest.py*
patch_2a_leak.a
patch_2a_leak.b
pix2img_all.py*
pix2img.py*
plotChiSquared.py*
plotPowerSpec.py*
plotPowerSpec.pyc
plotthingcode.py*
plotutils.py*
plotutils.pyc
prepMap2Cl.py*
prepMap2Cl.pyc
printMapStats.py*
printRunlist.py*
#processHist.py#*
processPowspec100826jz.py*
processPowspec.py*
processPowspec.py~*
processPowspec.pyc
processSidelobes.py*
processSQLMapChi2.py*
processSQL.py*
quiet.py
quiet.pyc
README
removeBadAccepts.py*
retired/
run/
scaleNoiseParams.py*
season-times.txt
secateur.py*
secateur.pyc
spectraChi2.py*
spliceGains.py*
splitGains.py*
splits/
static.cut
temp/
templates/
temp.txt
test.py
translateTypeBDirs.py*
trialcl.dat
weather_accept_input.txt
weather_cutlist.txt
